### ISSUE TITLE
User struct missing the `groups` key

### ISSUE THREAD

**Issue by robertmarsal** [auth0/go-auth0#146]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/go-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://pkg.go.dev/github.com/auth0/go-auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/go-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/go-auth0/releases/latest) of this SDK and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The `User` struct is not returning the `groups` value when called via the management API, however this gets returned when calling the API directly.

Would you be ok with me sending a PR adding this?

### Expectation

The `User` struct includes a groups property

### Reproduction

1. Given I use the users search management API via this SDK
2. I can't read the value of the `groups` because the `User` struct is not including it even thought the response is

### Auth0 Go SDK version

v0.14.0

**Comment by robertmarsal** [comment]
For now I got around this limitation by calling the API directly bypassing the SDK but it would be nice for the SDK to support retrieving all the fields the API returns and not just a subset

**Comment by sergiught** [comment]
Hey @robertmarsal 👋🏻 

Thanks for opening an issue. Would you mind offering a bit more context into the ask as this is not part of the public API schema found at https://auth0.com/docs/api/management/v2#!/Users/get_users_by_id. Something similar to this https://github.com/auth0/go-auth0/pull/153#issue-1557542390 would be great 🙇🏻 

Thanks!

**Comment by robertmarsal** [comment]
Hi @sergiught I probably don't have a solid argument on adding this to the `User` struct as this is an internal custom field used by my company however this is being returned by the API when calling it directly without using the SDK so there should be a way to read these values with the SDK as well for parity and consistency.

Maybe the `User` struct can contain an extra map field with all the non standard fields and consumers can read their custom values from there?

**Comment by sergiught** [comment]
Hey @robertmarsal thanks for the extra info! Indeed the `User` struct at the moment only supports the Auth0 API json tags and doesn't take into account that other identity providers could enhance the struct with additional fields. 

> Maybe the User struct can contain an extra map field with all the non standard fields and consumers can read their custom values from there?

This is something we'll have to discuss internally and find a solution for. Until then I'll set this issue as a feature request instead of a bug, as it would be more appropriate. I'll circle back when I have an update on this.

**Comment by ewanharris** [comment]
Hey @robertmarsal, we've added an example of how this can be achieved by creating a custom struct and using the `Request` func exposed by the management SDK to make requests rather than the SDKs `User` funcs. In a future release we might look to improve upon this but we want to make sure we expose this functionality in the right way.

You can check it out [here](https://github.com/auth0/go-auth0/blob/main/EXAMPLES.md#providing-a-custom-user-struct) and let me know if you have any questions!

**Comment by robertmarsal** [comment]
Hi @ewanharris that's great thank you. This is what we ended up doing in the end. I'm glad this is now documented. 

Happy to close this issue. Thank you.
