### ISSUE TITLE
Sdk itself handles request for Management Api Rate Limiting

### ISSUE THREAD

**Issue by sergiughf** [auth0/go-auth0#23]
From auth0 created by [sambhavjain9138](https://github.com/sambhavjain9138): go-auth0/auth0#261  

### Question
we are currently using this SDK to make management api calls. But we face some error due to management api rate limiting. Following is an article for the same. 
https://auth0.com/docs/troubleshoot/customer-support/operational-policies/rate-limit-policy/management-api-endpoint-rate-limits

During this request, auth0 returns a status code of 409, which helps us identify that the error is due to rate limiting. So can sdk itself make a small delay and then make a retry, during such responses? 

Even if it doesnt, How can we get this response status code in the response so as to make such check and introduce delay?

**Comment by sergiughf** [comment]
Hey @sambhavjain9138, apologies for the delay in answering this, the SDK already has a rate limiter configured on the client https://github.com/auth0/go-auth0/blob/14e9e2785341a61fb5ea21118add5c1d6f4d70a5/internal/client/client.go#L33-L38 so there's no need to handle retries manually. 

Let us know if you have any other questions!

**Comment by miparnisari** [comment]
@sergiught why does that only retry on 429s? Would it be possible to implement a general retry backoff mechanism to deal with other errors as well?

**Comment by sergiught** [comment]
Hey @miparnisari 👋🏻 , thanks for the inquiry! 

By default within the SDK we only retry on 429 (Rate Limits) as this gets hit quite often especially on free tier tenants. We don't usually want to retry on all other 400s because all of those are client errors, meaning something is wrong with the request so retrying won't help.

We could add by default retries on 500s as those are server error codes but this is unnecessary because they are extremely rare and in case of need the default http client can always be overridden with one that automatically retries on 500s by using the `WithClient()` func when instantiating the management client. The idea was to not make the SDK too opinionated and let folks extend this as needed. 

Let me know if you have any other questions! Happy to help clarify further.
