### ISSUE TITLE
failed to unmarshal response payload: invalid character 'W' looking for beginning of value

### ISSUE THREAD

**Issue by RobinLbt** [auth0/go-auth0#321]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/go-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://pkg.go.dev/github.com/auth0/go-auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/go-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/go-auth0/releases/latest) of this SDK and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm using the SDK to trigger a password reset:

```go
// Reset password method
func (a *Auth0) ResetPassword(userEmail string) error {

	type ChangePassword struct {
		ClientId   string `json:"client_id"`
		Email      string `json:"email"`
		Connection string `json:"connection"`
	}

	baseURL := "https://" + a.config.Auth0_domain + "/"

	err := a.Request(context.TODO(), http.MethodPost, baseURL+"dbconnections/change_password", &ChangePassword{
		ClientId:   a.config.Auth0_client_id,
		Email:      userEmail,
		Connection: "Username-Password-Authentication",
	},
	)

	if err != nil {
		return err
	}

	return nil
}

```

It returns an error:
```console
failed to unmarshal response payload: invalid character 'W' looking for begininng of value
```

Even though the reset password is sent, and users can safely reset the password

### Expectation

Ideally, it would be great to have a direct method to trigger a password reset with the SDK, without having to make an HTTP call manually (I guess this is a very common use case)

But in this case, using the Request method, it should be able to unmarshal the response, I guess this is a format issue?

### Reproduction

1. Call the `dbconnections/change_password` endpoint using the Request method of the Go Auth0 SDK with correct payload and Auth0 domain
2. You should receive the reset password email, but the response should throw an error because it can't be unmarshal

### Auth0 Go SDK version

1.3.1

**Comment by ewanharris** [comment]
Thanks for the issue @RobinLbt, the reason for this is that the change password endpoint doesn't return a JSON response but instead a string and the `Request` function expects to be able to decode the response as JSON.

We do offer an [authentication package](https://pkg.go.dev/github.com/auth0/go-auth0/authentication) since v1 which does include [this API call](https://pkg.go.dev/github.com/auth0/go-auth0/authentication#Database.ChangePassword) under the `Database` namespace, I think you should be able to replace your usage with this? I'm assuming that your `Auth0` type there is a `Management` client so you would have to create a new `Authentication` client to use this which there is an example of [here](https://pkg.go.dev/github.com/auth0/go-auth0/authentication)

**Comment by RobinLbt** [comment]
Perfect, thank you!

Should I close the issue?

**Comment by ewanharris** [comment]
No problem at all! I can close this out, thanks again for raising!
