### ISSUE TITLE
Pointers to Organization Metadata

### ISSUE THREAD

**Issue by miicchelle** [auth0/go-auth0#356]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/go-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://pkg.go.dev/github.com/auth0/go-auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/go-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/go-auth0/releases/latest) of this SDK and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I was going to submit this as a question but it didnt allow me to do that. Basically I am having a hard time implementing this version of the sdk because the metadata for both users and organizations are defined as pointers to a map. 
I am confused as to why we would use a pointer since map is already a reference type but also it makes it almost impossible to work with that data. Am I crazy and doing something wrong? I want to check if a metadata tag exists and if not create it. It was very easy to do it with the old sdk: https://github.com/go-auth0/auth0/tree/master 

### Expectation

My expectation would be for metadata to just be a map and not a pointer to a map

### Reproduction

n/a

### Auth0 Go SDK version

1.4.0

**Comment by developerkunal** [comment]
Hello @miicchelle,

I see why you’re puzzled by the use of a pointer for the Metadata field in the Organization struct — it can indeed seem a bit counterintuitive at first glance, especially since maps in Go are already reference types. This design choice is nuanced and is meant to enhance both the API’s flexibility and how data is managed internally.

Here’s why this approach can be quite beneficial:

**Optional Fields**: The pointer allows the Metadata to be completely optional. This helps in distinguishing cases where the metadata is not just empty but intentionally not provided, saving memory and avoiding unnecessary data processing.
**Memory Efficiency**: By using a pointer, memory allocation for the map only happens when it’s necessary. For applications where metadata might often be absent, this is an efficient approach.
**Serialization Clarity**: In JSON serialization, there’s a meaningful difference between an absent field (omitted from the JSON altogether) and an empty one (shown as {}). This distinction is important because it can influence how other systems interpret the data.

To manage the metadata effectively, especially if you need to check for a key or create one if it doesn’t exist, you can use a straightforward method:

```
func ensureMetadata(org *Organization, key, value string) {
    if org.Metadata == nil {
        org.Metadata = &map[string]string{}
    }

    if _, exists := (*org.Metadata)[key]; !exists {
        (*org.Metadata)[key] = value
    }
}

// Example of how you might use this
func main() {
    org := Organization{} // Other fields are assumed to be set or not needed for this example

    ensureMetadata(&org, "example", "value")

    if org.Metadata != nil {
        fmt.Println("Metadata:", *org.Metadata)
    }
}
```

This function will take care of initializing the Metadata if it’s not already set and will add a new key-value pair if your specified key doesn’t exist.

I understand this might feel a bit cumbersome compared to a direct map, but this method should make it manageable and help you adapt to the SDK’s current structure. If you have any more questions or need further assistance, please don’t hesitate to reach out. We’re here to help each other through these technical challenges!
